import { StyleSheet } from 'react-native';

const theme = {
  primaryColor: '#F97B22', // Naranja principal
  lightPrimaryColor: '#fff', // Fondo blanco
  textColor: '#333',
  white: '#FFFFFF',
  grey: '#888',
  lightGrey: '#EAEAEA',
  red: '#D9534F',
  blue: '#007BFF',
};

export const styles = StyleSheet.create({
  errorText: {
    color: '#e74c3c',
    fontSize: 12,
    marginTop: 4,
    fontStyle: 'italic',
  },
  container: {
    flex: 1,
    backgroundColor: theme.lightPrimaryColor,
    paddingTop: 50,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  sectionContainer: {
    marginHorizontal: 16,
    marginBottom: 12,
  },
  sectionHeader: {
    backgroundColor: theme.white,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: theme.primaryColor,
  },
  collapseIcon: {
    fontSize: 24,
    fontWeight: 'bold',
    color: theme.primaryColor,
  },
  expandedContent: {
    paddingTop: 16,
  },
  searchCreateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    height: 48,
    backgroundColor: theme.white,
    borderRadius: 10,
    paddingHorizontal: 16,
    fontSize: 16,
    borderColor: theme.lightGrey,
    borderWidth: 1,
    marginRight: 10,
  },
  createButton: {
    backgroundColor: theme.primaryColor,
    paddingHorizontal: 20,
    height: 48,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  createButtonText: {
    color: theme.white,
    fontWeight: 'bold',
    fontSize: 16,
  },
  resultsCount: {
    color: theme.primaryColor,
    marginBottom: 16,
    fontWeight: '500',
  },
  emptyListText: {
    textAlign: 'center',
    color: theme.grey,
    marginTop: 20,
    fontSize: 16,
  },
  listItemContainer: {
    backgroundColor: theme.white,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
    overflow: 'hidden',
  },
  listItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 16,
    backgroundColor: theme.lightGrey,
  },
  avatarPlaceholder: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: theme.lightGrey,
    marginRight: 16,
  },
  itemTextContainer: {
    flex: 1,
  },
  itemName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.textColor,
  },
  itemSubtitle: {
    fontSize: 14,
    color: theme.grey,
    marginTop: 2,
  },
  itemExpandIcon: {
    fontSize: 16,
    color: theme.grey,
  },
  actionsContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: theme.lightGrey,
    backgroundColor: '#FAFAFA',
  },
  actionButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginLeft: 10,
  },
  editButton: {
    backgroundColor: theme.blue,
  },
  deleteButton: {
    backgroundColor: theme.red,
  },
  actionText: {
    color: theme.white,
    fontWeight: 'bold',
  },
});

// --- ESTILOS DEL MODAL ---
export const modalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 20,
    width: '90%',
    maxHeight: '85%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 24,
    color: theme.primaryColor,
    textAlign: 'left',
  },
  fieldContainer: {
    marginBottom: 16,
  },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
    color: theme.grey,
  },
  input: {
    backgroundColor: '#F7F7F7',
    borderWidth: 1,
    borderColor: '#E8E8E8',
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    color: theme.textColor,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
    borderTopColor: '#f0f0f0',
    borderTopWidth: 1,
    paddingTop: 20,
  },
  submitButton: {
    backgroundColor: theme.primaryColor,
    paddingVertical: 14,
    borderRadius: 10,
    flex: 1,
    marginRight: 8,
    alignItems: 'center',
  },
  submitButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },
  cancelButton: {
    backgroundColor: '#EAEAEA',
    paddingVertical: 14,
    borderRadius: 10,
    flex: 1,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: theme.grey,
    fontWeight: 'bold',
    fontSize: 16,
  },
  imagePreview: {
    width: 120,
    height: 120,
    borderRadius: 12,
    marginBottom: 12,
    alignSelf: 'center',
    borderWidth: 2,
    borderColor: theme.lightGrey,
  },
  imagePickerButton: {
    // <-- CAMBIO: Color del botón a naranja
    backgroundColor: theme.primaryColor,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    alignSelf: 'center',
    marginBottom: 12,
  },
  imagePickerText: {
    color: 'white',
    fontWeight: 'bold',
  },
});