import {
  StyleSheet,
  Dimensions,
  Platform,
  StatusBar,
} from "react-native";

export const { width: screenWidth } = Dimensions.get("window");
export const scale = (size) => (screenWidth / 375) * size;

export const styles = StyleSheet.create({
  fullScreenContainer: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : scale(40),
    paddingBottom: scale(12),
    paddingHorizontal: scale(16),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: scale(1) },
    shadowOpacity: 0.1,
    shadowRadius: scale(1),
    elevation: scale(2),
    borderBottomWidth: StyleSheet.hairlineWidth * 2,
    borderBottomColor: "#e0e0e0",
  },
  contentSafeArea: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  backButton: {
    marginRight: scale(16),
    padding: scale(4),
  },
  backButtonText: {
    fontSize: scale(28),
    fontWeight: "bold",
    color: "#f57c00",
  },
  headerTitle: {
    fontSize: scale(20),
    fontWeight: "bold",
    color: "#333333",
  },
  centered: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    color: "red",
    textAlign: "center",
    fontSize: scale(16),
  },
  listContent: {
    paddingHorizontal: scale(16),
    paddingTop: scale(16),
    paddingBottom: scale(16),
  },
  emptyContainer: {
    padding: scale(16),
    alignItems: "center",
    marginTop: scale(40),
  },
  emptyText: {
    fontSize: scale(14),
    color: "#666",
  },

  // Card compacta
  card: {
    backgroundColor: "#fff",
    borderRadius: scale(20),
    padding: scale(16),
    alignItems: "center",
    marginBottom: scale(20),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: scale(2) },
    shadowOpacity: 0.08,
    shadowRadius: scale(6),
    elevation: scale(4),
    width: screenWidth - scale(32),
  },
  imageOuterContainer: {
    position: "relative",
    marginBottom: scale(16),
  },
  imageBorder: {
    width: scale(140),
    height: scale(140),
    borderRadius: scale(24),
    borderWidth: scale(4),
    borderColor: "#f57c00",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
    padding: scale(6),
  },
  cardImage: {
    width: "100%",
    height: "100%",
    borderRadius: scale(22),
  },
  imagePlaceholder: {
    width: "100%",
    height: "100%",
    borderRadius: scale(22),
    backgroundColor: "#f0f0f0",
    justifyContent: "center",
    alignItems: "center",
  },
  imagePlaceholderIcon: {
    fontSize: scale(40),
    color: "#cccccc",
  },
  trophyBadge: {
    position: "absolute",
    bottom: scale(-8),
    right: scale(-8),
    backgroundColor: "#f57c00",
    width: scale(36),
    height: scale(36),
    borderRadius: scale(18),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: scale(2),
    borderColor: "#fff",
  },
  trophyIcon: {
    fontSize: scale(18),
    color: "#fff",
  },
  cardTitle: {
    fontSize: scale(22),
    fontWeight: "bold",
    color: "#1c1c1c",
    textAlign: "center",
  },
  tagContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff5e6",
    borderRadius: scale(18),
    paddingHorizontal: scale(10),
    paddingVertical: scale(4),
    marginTop: scale(8),
  },
  tagIcon: {
    marginRight: scale(4),
    fontSize: scale(12),
  },
  tagText: {
    fontSize: scale(12),
    fontWeight: "600",
    color: "#d97706",
  },
  descriptionContainer: {
    backgroundColor: "#f8f9fa",
    borderRadius: scale(14),
    padding: scale(12),
    marginTop: scale(12),
    width: "100%",
  },
  cardDescription: {
    fontSize: scale(14),
    color: "#666",
    textAlign: "center",
    lineHeight: scale(20),
  },
  pointsContainer: {
    backgroundColor: "#fff8e1",
    borderRadius: scale(18),
    paddingVertical: scale(12),
    paddingHorizontal: scale(16),
    marginTop: scale(12),
    alignItems: "center",
    width: "100%",
  },
  pointsValue: {
    fontSize: scale(28),
    fontWeight: "bold",
    color: "#f57c00",
  },
  pointsLabel: {
    fontSize: scale(10),
    fontWeight: "600",
    color: "#b45309",
    marginTop: scale(2),
    letterSpacing: scale(0.5),
    textAlign: "center",
  },
  button: {
    backgroundColor: "#f57c00",
    borderRadius: scale(22),
    paddingVertical: scale(12),
    alignItems: "center",
    marginTop: scale(16),
    width: "100%",
  },
  buttonDisabled: {
    backgroundColor: "#ccc",
  },
  buttonLoading: {
    backgroundColor: "#d97706",
  },
  buttonText: {
    color: "#fff",
    fontSize: scale(14),
    fontWeight: "bold",
  },
});