import {
  StyleSheet,
  Dimensions,
  Platform, 
  StatusBar, 
} from "react-native";

const { width: screenWidth } = Dimensions.get("window");
const scale = (size) => (screenWidth / 375) * size;

export const styles = StyleSheet.create({
  fullScreenContainer: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    // Aquí es donde StatusBar y Platform son necesarios
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : scale(40),
    paddingBottom: scale(15),
    paddingHorizontal: scale(16),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: scale(2) },
    shadowOpacity: 0.05,
    shadowRadius: scale(2),
    elevation: scale(3),
    borderBottomWidth: StyleSheet.hairlineWidth * 2,
    borderBottomColor: "#e0e0e0",
  },
  contentSafeArea: {
    flex: 1,
    backgroundColor: "#f8f9fa",
  },
  backButton: { marginRight: scale(16), padding: scale(4) },
  backButtonText: {
    fontSize: scale(28),
    fontWeight: "bold",
    color: "#f57c00",
  },
  headerTitle: {
    fontSize: scale(20),
    fontWeight: "bold",
    color: "#333333",
  },
  centeredContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: scale(20),
  },
  errorText: { color: "red", textAlign: "center", fontSize: scale(16) },
  emptyText: { fontSize: scale(16), color: "#666" },
  listContent: {
    paddingHorizontal: scale(16),
    paddingTop: scale(20),
    paddingBottom: scale(20),
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: scale(24),
    padding: scale(20),
    alignItems: "center",
    marginBottom: scale(25),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: scale(4) },
    shadowOpacity: 0.1,
    shadowRadius: scale(10),
    elevation: scale(8),
  },
  imageOuterContainer: {
    position: "relative",
    marginBottom: scale(20),
  },
  imageBorder: {
    width: scale(180),
    height: scale(180),
    borderRadius: scale(30),
    borderWidth: scale(6),
    borderColor: "#f57c00",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
    padding: scale(8),
  },
  cardImage: {
    width: "100%",
    height: "100%",
    borderRadius: scale(22),
  },
  imagePlaceholder: {
    width: "100%",
    height: "100%",
    borderRadius: scale(22),
    backgroundColor: "#f0f0f0",
    justifyContent: "center",
    alignItems: "center",
  },
  imagePlaceholderIcon: { fontSize: scale(50), color: "#cccccc" },
  starBadge: {
    position: "absolute",
    bottom: scale(-10),
    right: scale(-10),
    backgroundColor: "#f57c00",
    width: scale(44),
    height: scale(44),
    borderRadius: scale(12),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: scale(3),
    borderColor: "#fff",
  },
  starIcon: { fontSize: scale(22), color: "#fff" },
  cardTitle: {
    fontSize: scale(22),
    fontWeight: "bold",
    color: "#1c1c1c",
    textAlign: "center",
  },
  tagContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff5e6",
    borderRadius: scale(20),
    paddingHorizontal: scale(12),
    paddingVertical: scale(6),
    marginTop: scale(10),
  },
  tagIcon: { marginRight: scale(6), fontSize: scale(14) },
  tagText: {
    fontSize: scale(14),
    fontWeight: "600",
    color: "#d97706",
  },
  descriptionContainer: {
    backgroundColor: "#f8f9fa",
    borderRadius: scale(16),
    padding: scale(16),
    marginTop: scale(20),
    width: "100%",
  },
  cardDescription: {
    fontSize: scale(15),
    color: "#666",
    textAlign: "center",
    lineHeight: scale(22),
  },
  infoRow: {
    flexDirection: "row",
    marginTop: scale(20),
    width: "100%",
    justifyContent: "space-between",
  },
  pointsBox: {
    flex: 1,
    backgroundColor: "#fff8e1",
    borderRadius: scale(20),
    padding: scale(16),
    alignItems: "center",
    marginRight: scale(8),
  },
  availableBox: {
    flex: 1,
    backgroundColor: "#e6f7ec",
    borderRadius: scale(20),
    padding: scale(16),
    alignItems: "center",
    marginLeft: scale(8),
  },
  pointsValue: {
    fontSize: scale(24),
    fontWeight: "bold",
    color: "#f57c00",
  },
  pointsLabel: {
    fontSize: scale(12),
    fontWeight: "600",
    color: "#b45309",
    marginTop: scale(4),
  },
  availableValue: {
    fontSize: scale(24),
    fontWeight: "bold",
    color: "#28a745",
  },
  availableLabel: {
    fontSize: scale(12),
    fontWeight: "600",
    color: "#155724",
    marginTop: scale(4),
  },
  button: {
    backgroundColor: "#f57c00",
    borderRadius: scale(25),
    paddingVertical: scale(16),
    alignItems: "center",
    marginTop: scale(20),
    width: "100%",
  },
  buttonDisabled: { backgroundColor: "#ccc" },
  buttonLoading: {
    backgroundColor: "#d97706", // Un tono diferente de naranja o gris para indicar carga
  },
  buttonText: {
    color: "#fff",
    fontSize: scale(16),
    fontWeight: "bold",
  },
});